### ISSUE TITLE
Unclear Documentation

### ISSUE THREAD

**Issue by LTFENG** [Fjessin2/flipperclock#2]
Dear Author, 

I would like to implement your library in my project, because I want to make a flip animation count down timer.

Btw, I don't know how to implement it in my project, I did follow your 2 steps, but still my project cannot find your library. 

Hope you can help me

Thanks a lot. Great work!

**Comment by Fjessin2** [comment]
Dear LTFENG,

I see there was an error, in the documentation's 2. step.
I have now updated it. Could you try to implement the 2. step, and see if your project is able to find this library?

Kind regards
Frederik
